### PR TITLE
Migrate to register_signed_statement

### PR DESCRIPTION
**Pull request by SteveLasker**
Also, includes: creating transparent_statement

### CODE REVIEW

**Comment by SteveLasker** [comment]
This is in draft mode as we moved to a script, which is far simpler, and more robust for error handling. However, the current script doesn't generate the Entry_ID used for Veracity.

To complete this draft, we need to fill the gap for retrieving the Entry_Id to pas to veracity

**Comment by SteveLasker** [comment]
Removed veracity checks to get this change in, keeping in synch with scitt-samples

**Comment by SteveLasker** [comment]
Should be committed with https://github.com/datatrails/datatrails-scitt-samples/pull/21

**Review by JAG-UK — APPROVED** [review]
Lgtm

**Pull request merged**
